## 本次作業使用Kaggle上，預測「鐵達尼號存活率」的，非常經典的例子，請先下載本檔案做使用，需要把這個檔案放在跟 jupyter notebook同一個資料夾才讀取的到

### 我們今天的目標，是利用其中的「性別 Sex」跟「年齡 Age」來預測「存活與否 Survived」(1是存活，0則否）。

1.首先，請使用pandas套件讀檔

2.請取出所有的Age跟Sex作為題目，和Survived做為答案並分成三個同名的numpy array。 (提示： Age.shape = (891, ))

3.其中，由於Age有一些值是空值NaN，請把這些空值都先換成0。提示： 可使用 np.isnan(某個你想確認是不是NaN的年齡) ）

4.再來，Sex部分因為都是文字，不方便我們做svm，請把Male都換成0，Female都換成1 

5.由於我們想把Sex跟Age都當成data，請把Sex和Age兩個array合併成一個。（提示：先用np.reshape，再用np.append）

6.實際拿svm 訓練看看，並用同樣的data，preict看看結果（這次不用分training data跟testing data）

加分題： 請設計一種方法，比較看看你的預測結果，和正確答案(Survived)，找出你的「預測正確率」是多少。

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("train.csv")

In [6]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [14]:
sex = np.array(df.Sex)
age = np.array(df.Age)
survived = np.array(df.Survived)

In [26]:
for i in range(sex.shape[0]):
    if sex[i] == 'male':
        sex[i] = 0
    else:
        sex[i] = 1

In [27]:
sex

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0], dtype=object)

In [33]:
for i in range(age.shape[0]):
    if np.isnan(age[i]):
        age[i] = 0

In [34]:
age

array([22.  , 38.  , 26.  , 35.  , 35.  ,  0.  , 54.  ,  2.  , 27.  ,
       14.  ,  4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  ,  0.  ,
       31.  ,  0.  , 35.  , 34.  , 15.  , 28.  ,  8.  , 38.  ,  0.  ,
       19.  ,  0.  ,  0.  , 40.  ,  0.  ,  0.  , 66.  , 28.  , 42.  ,
        0.  , 21.  , 18.  , 14.  , 40.  , 27.  ,  0.  ,  3.  , 19.  ,
        0.  ,  0.  ,  0.  ,  0.  , 18.  ,  7.  , 21.  , 49.  , 29.  ,
       65.  ,  0.  , 21.  , 28.5 ,  5.  , 11.  , 22.  , 38.  , 45.  ,
        4.  ,  0.  ,  0.  , 29.  , 19.  , 17.  , 26.  , 32.  , 16.  ,
       21.  , 26.  , 32.  , 25.  ,  0.  ,  0.  ,  0.83, 30.  , 22.  ,
       29.  ,  0.  , 28.  , 17.  , 33.  , 16.  ,  0.  , 23.  , 24.  ,
       29.  , 20.  , 46.  , 26.  , 59.  ,  0.  , 71.  , 23.  , 34.  ,
       34.  , 28.  ,  0.  , 21.  , 33.  , 37.  , 28.  , 21.  ,  0.  ,
       38.  ,  0.  , 47.  , 14.5 , 22.  , 20.  , 17.  , 21.  , 70.5 ,
       29.  , 24.  ,  2.  , 21.  ,  0.  , 32.5 , 32.5 , 54.  , 12.  ,
        0.  , 24.  ,  0.  , 45.  , 33.  , 20.  , 47.  , 29.  , 25.  ,
       23.  , 19.  , 37.  , 16.  , 24.  ,  0.  , 22.  , 24.  , 19.  ,
       18.  , 19.  , 27.  ,  9.  , 36.5 , 42.  , 51.  , 22.  , 55.5 ,
       40.5 ,  0.  , 51.  , 16.  , 30.  ,  0.  ,  0.  , 44.  , 40.  ,
       26.  , 17.  ,  1.  ,  9.  ,  0.  , 45.  ,  0.  , 28.  , 61.  ,
        4.  ,  1.  , 21.  , 56.  , 18.  ,  0.  , 50.  , 30.  , 36.  ,
        0.  ,  0.  ,  9.  ,  1.  ,  4.  ,  0.  ,  0.  , 45.  , 40.  ,
       36.  , 32.  , 19.  , 19.  ,  3.  , 44.  , 58.  ,  0.  , 42.  ,
        0.  , 24.  , 28.  ,  0.  , 34.  , 45.5 , 18.  ,  2.  , 32.  ,
       26.  , 16.  , 40.  , 24.  , 35.  , 22.  , 30.  ,  0.  , 31.  ,
       27.  , 42.  , 32.  , 30.  , 16.  , 27.  , 51.  ,  0.  , 38.  ,
       22.  , 19.  , 20.5 , 18.  ,  0.  , 35.  , 29.  , 59.  ,  5.  ,
       24.  ,  0.  , 44.  ,  8.  , 19.  , 33.  ,  0.  ,  0.  , 29.  ,
       22.  , 30.  , 44.  , 25.  , 24.  , 37.  , 54.  ,  0.  , 29.  ,
       62.  , 30.  , 41.  , 29.  ,  0.  , 30.  , 35.  , 50.  ,  0.  ,
        3.  , 52.  , 40.  ,  0.  , 36.  , 16.  , 25.  , 58.  , 35.  ,
        0.  , 25.  , 41.  , 37.  ,  0.  , 63.  , 45.  ,  0.  ,  7.  ,
       35.  , 65.  , 28.  , 16.  , 19.  ,  0.  , 33.  , 30.  , 22.  ,
       42.  , 22.  , 26.  , 19.  , 36.  , 24.  , 24.  ,  0.  , 23.5 ,
        2.  ,  0.  , 50.  ,  0.  ,  0.  , 19.  ,  0.  ,  0.  ,  0.92,
        0.  , 17.  , 30.  , 30.  , 24.  , 18.  , 26.  , 28.  , 43.  ,
       26.  , 24.  , 54.  , 31.  , 40.  , 22.  , 27.  , 30.  , 22.  ,
        0.  , 36.  , 61.  , 36.  , 31.  , 16.  ,  0.  , 45.5 , 38.  ,
       16.  ,  0.  ,  0.  , 29.  , 41.  , 45.  , 45.  ,  2.  , 24.  ,
       28.  , 25.  , 36.  , 24.  , 40.  ,  0.  ,  3.  , 42.  , 23.  ,
        0.  , 15.  , 25.  ,  0.  , 28.  , 22.  , 38.  ,  0.  ,  0.  ,
       40.  , 29.  , 45.  , 35.  ,  0.  , 30.  , 60.  ,  0.  ,  0.  ,
       24.  , 25.  , 18.  , 19.  , 22.  ,  3.  ,  0.  , 22.  , 27.  ,
       20.  , 19.  , 42.  ,  1.  , 32.  , 35.  ,  0.  , 18.  ,  1.  ,
       36.  ,  0.  , 17.  , 36.  , 21.  , 28.  , 23.  , 24.  , 22.  ,
       31.  , 46.  , 23.  , 28.  , 39.  , 26.  , 21.  , 28.  , 20.  ,
       34.  , 51.  ,  3.  , 21.  ,  0.  ,  0.  ,  0.  , 33.  ,  0.  ,
       44.  ,  0.  , 34.  , 18.  , 30.  , 10.  ,  0.  , 21.  , 29.  ,
       28.  , 18.  ,  0.  , 28.  , 19.  ,  0.  , 32.  , 28.  ,  0.  ,
       42.  , 17.  , 50.  , 14.  , 21.  , 24.  , 64.  , 31.  , 45.  ,
       20.  , 25.  , 28.  ,  0.  ,  4.  , 13.  , 34.  ,  5.  , 52.  ,
       36.  ,  0.  , 30.  , 49.  ,  0.  , 29.  , 65.  ,  0.  , 50.  ,
        0.  , 48.  , 34.  , 47.  , 48.  ,  0.  , 38.  ,  0.  , 56.  ,
        0.  ,  0.75,  0.  , 38.  , 33.  , 23.  , 22.  ,  0.  , 34.  ,
       29.  , 22.  ,  2.  ,  9.  ,  0.  , 50.  , 63.  , 25.  ,  0.  ,
       35.  , 58.  , 30.  ,  9.  ,  0.  , 21.  , 55.  , 71.  , 21.  ,
        0.  , 54.  ,  0.  , 25.  , 24.  , 17.  , 21.  ,  0.  , 37.  ,
       16.  , 18.  , 33.  ,  0.  , 28.  , 26.  , 29.  ,  0.  , 36.  ,
       54.  , 24.  , 47.  , 34.  ,  0.  , 36.  , 32.  , 30.  , 22.  ,
        0.  , 44.  ,  0.  , 40.5 , 50.  ,  0.  , 39.  , 23.  ,  2.  ,
        0.  , 17.  ,  0.  , 30.  ,  7.  , 45.  , 30.  ,  0.  , 22.  ,
       36.  ,  9.  , 11.  , 32.  , 50.  , 64.  , 19.  ,  0.  , 33.  ,
        8.  , 17.  , 27.  ,  0.  , 22.  , 22.  , 62.  , 48.  ,  0.  ,
       39.  , 36.  ,  0.  , 40.  , 28.  ,  0.  ,  0.  , 24.  , 19.  ,
       29.  ,  0.  , 32.  , 62.  , 53.  , 36.  ,  0.  , 16.  , 19.  ,
       34.  , 39.  ,  0.  , 32.  , 25.  , 39.  , 54.  , 36.  ,  0.  ,
       18.  , 47.  , 60.  , 22.  ,  0.  , 35.  , 52.  , 47.  ,  0.  ,
       37.  , 36.  ,  0.  , 49.  ,  0.  , 49.  , 24.  ,  0.  ,  0.  ,
       44.  , 35.  , 36.  , 30.  , 27.  , 22.  , 40.  , 39.  ,  0.  ,
        0.  ,  0.  , 35.  , 24.  , 34.  , 26.  ,  4.  , 26.  , 27.  ,
       42.  , 20.  , 21.  , 21.  , 61.  , 57.  , 21.  , 26.  ,  0.  ,
       80.  , 51.  , 32.  ,  0.  ,  9.  , 28.  , 32.  , 31.  , 41.  ,
        0.  , 20.  , 24.  ,  2.  ,  0.  ,  0.75, 48.  , 19.  , 56.  ,
        0.  , 23.  ,  0.  , 18.  , 21.  ,  0.  , 18.  , 24.  ,  0.  ,
       32.  , 23.  , 58.  , 50.  , 40.  , 47.  , 36.  , 20.  , 32.  ,
       25.  ,  0.  , 43.  ,  0.  , 40.  , 31.  , 70.  , 31.  ,  0.  ,
       18.  , 24.5 , 18.  , 43.  , 36.  ,  0.  , 27.  , 20.  , 14.  ,
       60.  , 25.  , 14.  , 19.  , 18.  , 15.  , 31.  ,  4.  ,  0.  ,
       25.  , 60.  , 52.  , 44.  ,  0.  , 49.  , 42.  , 18.  , 35.  ,
       18.  , 25.  , 26.  , 39.  , 45.  , 42.  , 22.  ,  0.  , 24.  ,
        0.  , 48.  , 29.  , 52.  , 19.  , 38.  , 27.  ,  0.  , 33.  ,
        6.  , 17.  , 34.  , 50.  , 27.  , 20.  , 30.  ,  0.  , 25.  ,
       25.  , 29.  , 11.  ,  0.  , 23.  , 23.  , 28.5 , 48.  , 35.  ,
        0.  ,  0.  ,  0.  , 36.  , 21.  , 24.  , 31.  , 70.  , 16.  ,
       30.  , 19.  , 31.  ,  4.  ,  6.  , 33.  , 23.  , 48.  ,  0.67,
       28.  , 18.  , 34.  , 33.  ,  0.  , 41.  , 20.  , 36.  , 16.  ,
       51.  ,  0.  , 30.5 ,  0.  , 32.  , 24.  , 48.  , 57.  ,  0.  ,
       54.  , 18.  ,  0.  ,  5.  ,  0.  , 43.  , 13.  , 17.  , 29.  ,
        0.  , 25.  , 25.  , 18.  ,  8.  ,  1.  , 46.  ,  0.  , 16.  ,
        0.  ,  0.  , 25.  , 39.  , 49.  , 31.  , 30.  , 30.  , 34.  ,
       31.  , 11.  ,  0.42, 27.  , 31.  , 39.  , 18.  , 39.  , 33.  ,
       26.  , 39.  , 35.  ,  6.  , 30.5 ,  0.  , 23.  , 31.  , 43.  ,
       10.  , 52.  , 27.  , 38.  , 27.  ,  2.  ,  0.  ,  0.  ,  1.  ,
        0.  , 62.  , 15.  ,  0.83,  0.  , 23.  , 18.  , 39.  , 21.  ,
        0.  , 32.  ,  0.  , 20.  , 16.  , 30.  , 34.5 , 17.  , 42.  ,
        0.  , 35.  , 28.  ,  0.  ,  4.  , 74.  ,  9.  , 16.  , 44.  ,
       18.  , 45.  , 51.  , 24.  ,  0.  , 41.  , 21.  , 48.  ,  0.  ,
       24.  , 42.  , 27.  , 31.  ,  0.  ,  4.  , 26.  , 47.  , 33.  ,
       47.  , 28.  , 15.  , 20.  , 19.  ,  0.  , 56.  , 25.  , 33.  ,
       22.  , 28.  , 25.  , 39.  , 27.  , 19.  ,  0.  , 26.  , 32.  ])

In [36]:
age.shape

(891,)

In [46]:
sex = sex.reshape(-1, 1)
age = age.reshape(-1, 1)
sex_age = np.append(sex, age, axis = 1)

In [47]:
from sklearn.svm import SVC

In [49]:
model = SVC(gamma = 'auto')
model.fit(sex_age, survived)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [64]:
survived_predict = model.predict(sex_age)
model.predict(sex_age)

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0], dtype=int64)

In [65]:
#預測正確率
acc = survived[survived_predict == survived].shape[0]/survived.shape[0]
survived[survived_predict == survived].shape[0]/survived.shape[0]

0.8080808080808081

In [66]:
# 也可以直接用model.score
model.score(sex_age, survived)

0.8080808080808081

In [67]:
print(f"預測正確率為: {round(acc*100, 2)} %")

預測正確率為: 80.81 %